spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: kasra123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
